### ISSUE TITLE
Update backend fetch URLs for Jamulus Explorer

### ISSUE THREAD

**Issue by softins** [mcfnord/JamFan22#4]
https://github.com/mcfnord/JamFan22/blob/5e60c6eb2f270dfb5be44a119298741279ada2fc/JamFan22/Pages/Index.cshtml.cs#L96-L104

https://github.com/mcfnord/JamFan22/blob/5e60c6eb2f270dfb5be44a119298741279ada2fc/JamFan22/Pages/Index.cshtml.cs#L793-L802

In this file, there are several references to `jamulus.softins.co.uk`. This hostname was superseded two or three years ago by `explorer.jamulus.io`, although the old hostname remained for compatibility.

I have now removed `servers.php` from `jamulus.softins.co.uk`, so you need to update the above file to use `explorer.jamulus.io` instead. I can see in my logs for the old domain since yesterday a lot of failed requests for anygenre3, rock and choral.

Thanks, Tony

**Comment by mcfnord** [comment]
Oh my gosh! Thank you for this clue! I knew something seemed off.

**Comment by softins** [comment]
Cool, I can confirm requests are now going to the right place. Thanks!

You still need to change a couple of references though, in the fallback code:

https://github.com/mcfnord/JamFan22/blob/29dbab99284d2bfa871d2df9bcbead35ff1b3c59/JamFan22/Pages/Index.cshtml.cs#L805-L814

**Comment by mcfnord** [comment]
It's commented out tho!

**Comment by softins** [comment]
> It's commented out tho!

Hehe, I hadn't noticed that. But I still like to keep temporarily-disabled code up to date, in case I ever decide to re-activate it for some reason, to avoid having to wonder why it no longer works!
